### ISSUE TITLE
[nrpe] check retry interval should be configurable

### ISSUE THREAD

**Issue by aguadoenzo** [canonical/nats-operator#12]
The current retry timings are nagios' defaults, e.g. 5 minutes between checks, and 1 minute if the check failed
We should be able to configure those, as knowing the service is down 5 minutes later is not really useful

see `retry_interval`, `check_interval` and `max_check_attempts`
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html#service

**Comment by jat-canonical** [comment]
These no longer apply as we do not support LMA stack anymore.
